// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_apps_layout from "./routes/(apps)/_layout.tsx";
import * as $_apps_mobility_api_insert_students from "./routes/(apps)/mobility/api/insert_students.ts";
import * as $_apps_mobility_index from "./routes/(apps)/mobility/index.tsx";
import * as $_apps_mobility_partials_admin_mobility from "./routes/(apps)/mobility/partials/(admin)/mobility.tsx";
import * as $_apps_mobility_partials_index from "./routes/(apps)/mobility/partials/index.tsx";
import * as $_apps_mobility_partials_overview from "./routes/(apps)/mobility/partials/overview.tsx";
import * as $_apps_mobility_partials_students from "./routes/(apps)/mobility/partials/students.tsx";
import * as $_apps_notes_index from "./routes/(apps)/notes/index.tsx";
import * as $_apps_notes_partials_admin_courses from "./routes/(apps)/notes/partials/(admin)/courses.tsx";
import * as $_apps_notes_partials_index from "./routes/(apps)/notes/partials/index.tsx";
import * as $_apps_notes_partials_notes from "./routes/(apps)/notes/partials/notes.tsx";
import * as $_apps_students_api_example from "./routes/(apps)/students/api/example.ts";
import * as $_apps_students_index from "./routes/(apps)/students/index.tsx";
import * as $_apps_students_partials_index from "./routes/(apps)/students/partials/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $apps from "./routes/apps.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $_islands_AppNavigator from "./routes/(_islands)/AppNavigator.tsx";
import * as $_islands_Navbar from "./routes/(_islands)/Navbar.tsx";
import * as $_apps_mobility_islands_ConsultMobility from "./routes/(apps)/mobility/(_islands)/ConsultMobility.tsx";
import * as $_apps_mobility_islands_ConsultStudents from "./routes/(apps)/mobility/(_islands)/ConsultStudents.tsx";
import * as $_apps_mobility_islands_EditMobility from "./routes/(apps)/mobility/(_islands)/EditMobility.tsx";
import * as $_apps_mobility_islands_EditStudents from "./routes/(apps)/mobility/(_islands)/EditStudents.tsx";
import * as $_apps_mobility_islands_ImportFile from "./routes/(apps)/mobility/(_islands)/ImportFile.tsx";
import * as $_apps_mobility_islands_UploadStudents from "./routes/(apps)/mobility/(_islands)/UploadStudents.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(apps)/_layout.tsx": $_apps_layout,
    "./routes/(apps)/mobility/api/insert_students.ts":
      $_apps_mobility_api_insert_students,
    "./routes/(apps)/mobility/index.tsx": $_apps_mobility_index,
    "./routes/(apps)/mobility/partials/(admin)/mobility.tsx":
      $_apps_mobility_partials_admin_mobility,
    "./routes/(apps)/mobility/partials/index.tsx":
      $_apps_mobility_partials_index,
    "./routes/(apps)/mobility/partials/overview.tsx":
      $_apps_mobility_partials_overview,
    "./routes/(apps)/mobility/partials/students.tsx":
      $_apps_mobility_partials_students,
    "./routes/(apps)/notes/index.tsx": $_apps_notes_index,
    "./routes/(apps)/notes/partials/(admin)/courses.tsx":
      $_apps_notes_partials_admin_courses,
    "./routes/(apps)/notes/partials/index.tsx": $_apps_notes_partials_index,
    "./routes/(apps)/notes/partials/notes.tsx": $_apps_notes_partials_notes,
    "./routes/(apps)/students/api/example.ts": $_apps_students_api_example,
    "./routes/(apps)/students/index.tsx": $_apps_students_index,
    "./routes/(apps)/students/partials/index.tsx":
      $_apps_students_partials_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/apps.tsx": $apps,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
  },
  islands: {
    "./routes/(_islands)/AppNavigator.tsx": $_islands_AppNavigator,
    "./routes/(_islands)/Navbar.tsx": $_islands_Navbar,
    "./routes/(apps)/mobility/(_islands)/ConsultMobility.tsx":
      $_apps_mobility_islands_ConsultMobility,
    "./routes/(apps)/mobility/(_islands)/ConsultStudents.tsx":
      $_apps_mobility_islands_ConsultStudents,
    "./routes/(apps)/mobility/(_islands)/EditMobility.tsx":
      $_apps_mobility_islands_EditMobility,
    "./routes/(apps)/mobility/(_islands)/EditStudents.tsx":
      $_apps_mobility_islands_EditStudents,
    "./routes/(apps)/mobility/(_islands)/ImportFile.tsx":
      $_apps_mobility_islands_ImportFile,
    "./routes/(apps)/mobility/(_islands)/UploadStudents.tsx":
      $_apps_mobility_islands_UploadStudents,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
